//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ed.Steamflix.Mocks {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ed.Steamflix.Mocks.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Steam Community :: The Witcher 3: Wild Hunt&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	&lt;link href=&quot;http://steamcommunity-a.akamaihd.net/public/shared/css/motiva_sans.css?v=F3z3QpekjE2f&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; &gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BroadcastsHtml292030 {
            get {
                return ResourceManager.GetString("BroadcastsHtml292030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;friendslist&quot;: {
        ///		&quot;friends&quot;: [
        ///			{
        ///				&quot;steamid&quot;: &quot;76561197961947067&quot;,
        ///				&quot;relationship&quot;: &quot;friend&quot;,
        ///				&quot;friend_since&quot;: 1377244904
        ///			},
        ///			{
        ///				&quot;steamid&quot;: &quot;76561197966204794&quot;,
        ///				&quot;relationship&quot;: &quot;friend&quot;,
        ///				&quot;friend_since&quot;: 1387481620
        ///			},
        ///			{
        ///				&quot;steamid&quot;: &quot;76561197968580199&quot;,
        ///				&quot;relationship&quot;: &quot;friend&quot;,
        ///				&quot;friend_since&quot;: 1377643611
        ///			},
        ///			{
        ///				&quot;steamid&quot;: &quot;76561197970693534&quot;,
        ///				&quot;relationship&quot;: &quot;friend&quot;,
        ///				&quot;friend_since&quot;: 1377260639
        ///			},
        ///			{
        ///				&quot;steamid&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetFriendListResponseJson {
            get {
                return ResourceManager.GetString("GetFriendListResponseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;appnews&quot;: {
        ///		&quot;appid&quot;: 440,
        ///		&quot;newsitems&quot;: [
        ///			{
        ///				&quot;gid&quot;: &quot;552009088092503181&quot;,
        ///				&quot;title&quot;: &quot;Team Fortress 2 s Workshop Now Accepts Merchandise&quot;,
        ///				&quot;url&quot;: &quot;http://store.steampowered.com/news/externalpost/rps/552009088092503181&quot;,
        ///				&quot;is_external_url&quot;: true,
        ///				&quot;author&quot;: &quot;contact@rockpapershotgun.com (Graham Smith)&quot;,
        ///				&quot;contents&quot;: &quot;&lt;p&gt;&lt;img src=\&quot;http://www.rockpapershotgun.com/images/14/aug/tf2merchandise.jpg\&quot; alt=\&quot;Don&apos;t worry, it&apos;s mostly t-shirts.\&quot; /&gt;&lt;/p&gt;\n&lt;p&gt;&lt;a href=\&quot;http://www. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetNewsForAppResponseJson {
            get {
                return ResourceManager.GetString("GetNewsForAppResponseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;game_count&quot;: 199,
        ///		&quot;games&quot;: [
        ///			{
        ///				&quot;appid&quot;: 10,
        ///				&quot;name&quot;: &quot;Counter-Strike&quot;,
        ///				&quot;playtime_forever&quot;: 0,
        ///				&quot;img_icon_url&quot;: &quot;6b0312cda02f5f777efa2f3318c307ff9acafbb5&quot;,
        ///				&quot;img_logo_url&quot;: &quot;af890f848dd606ac2fd4415de3c3f5e7a66fcb9f&quot;,
        ///				&quot;has_community_visible_stats&quot;: true
        ///			},
        ///			{
        ///				&quot;appid&quot;: 20,
        ///				&quot;name&quot;: &quot;Team Fortress Classic&quot;,
        ///				&quot;playtime_forever&quot;: 0,
        ///				&quot;img_icon_url&quot;: &quot;38ea7ebe3c1abbbbf4eabdbef174c41a972102b9&quot;,
        ///				&quot;img_logo_url&quot;: &quot;515bc393c861d91b9165 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetOwnedGamesResponseJson {
            get {
                return ResourceManager.GetString("GetOwnedGamesResponseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;players&quot;: [
        ///			{
        ///				&quot;steamid&quot;: &quot;76561198084024217&quot;,
        ///				&quot;communityvisibilitystate&quot;: 3,
        ///				&quot;profilestate&quot;: 1,
        ///				&quot;personaname&quot;: &quot;trogidae&quot;,
        ///				&quot;lastlogoff&quot;: 1455660378,
        ///				&quot;commentpermission&quot;: 1,
        ///				&quot;profileurl&quot;: &quot;http://steamcommunity.com/profiles/76561198084024217/&quot;,
        ///				&quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/52/52fe41207d1ddf8c7fe1265d733c08501772ca22.jpg&quot;,
        ///				&quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/pub [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetPlayerSummariesResponseJson {
            get {
                return ResourceManager.GetString("GetPlayerSummariesResponseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;total_count&quot;: 15,
        ///		&quot;games&quot;: [
        ///			{
        ///				&quot;appid&quot;: 107410,
        ///				&quot;name&quot;: &quot;Arma 3&quot;,
        ///				&quot;playtime_2weeks&quot;: 306,
        ///				&quot;playtime_forever&quot;: 2167,
        ///				&quot;img_icon_url&quot;: &quot;3212af52faf994c558bd622cb0f360c1ef295a6b&quot;,
        ///				&quot;img_logo_url&quot;: &quot;b49962441a01f1f80b180af1293608dddf7df6b0&quot;
        ///			},
        ///			{
        ///				&quot;appid&quot;: 221380,
        ///				&quot;name&quot;: &quot;Age of Empires II: HD Edition&quot;,
        ///				&quot;playtime_2weeks&quot;: 246,
        ///				&quot;playtime_forever&quot;: 2049,
        ///				&quot;img_icon_url&quot;: &quot;109c74df17f9b67ea47d8f01e3d1ec25278b9f73&quot;,
        ///				&quot;img_lo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetRecentlyPlayedGamesResponseJson {
            get {
                return ResourceManager.GetString("GetRecentlyPlayedGamesResponseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;72850&quot;: {
        ///        &quot;success&quot;: true,
        ///        &quot;data&quot;: {
        ///            &quot;type&quot;: &quot;game&quot;,
        ///            &quot;name&quot;: &quot;The Elder Scrolls V: Skyrim&quot;,
        ///            &quot;steam_appid&quot;: 72850,
        ///            &quot;required_age&quot;: &quot;18&quot;,
        ///            &quot;is_free&quot;: false,
        ///            &quot;dlc&quot;: [
        ///                226880,
        ///                220760,
        ///                211720,
        ///                202485
        ///            ],
        ///            &quot;detailed_description&quot;: &quot;&lt;strong&gt;EPIC FANTASY REBORN&lt;/strong&gt;\r&lt;br&gt;\t\t\t\t\t\t\tThe next chapter in the highly antic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string httpstoresteampoweredcomapiappdetailsappids72850 {
            get {
                return ResourceManager.GetString("httpstoresteampoweredcomapiappdetailsappids72850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;steamid&quot;: &quot;76561197974081377&quot;,
        ///		&quot;success&quot;: 1
        ///	}
        ///}.
        /// </summary>
        public static string ResolveVanityUrlResponseJson {
            get {
                return ResourceManager.GetString("ResolveVanityUrlResponseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Steam: Game and Player Statistics&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	&lt;link href=&quot;http://store.akamai.steamstatic.com/public/shared/css/motiva_sans.css?v=qup8GBWmVxiv&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; &gt;
        ///&lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StatsHtml {
            get {
                return ResourceManager.GetString("StatsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sessionid=bfd5e0e9eb42560742234302; path=/,steamCountry=LV%7C6e52c8252a5042e90dec8a1634d40ebd; path=/.
        /// </summary>
        public static string SteamCookies {
            get {
                return ResourceManager.GetString("SteamCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;success&quot;:1,&quot;search_text&quot;:&quot;eadgar&quot;,&quot;search_filter&quot;:&quot;users&quot;,&quot;search_page&quot;:1,&quot;html&quot;:&quot;\t\t&lt;div style=\&quot;float: right; padding-bottom: 2px\&quot;&gt;\r\n\t\t\t\t\t\tShowing 1 - 15 of 15\t\t\t&lt;\/div&gt;\r\n\t&lt;div style=\&quot;clear: both\&quot;&gt;&lt;\/div&gt;\r\n\t\t\t\t\t\t&lt;div class=\&quot;search_row\&quot;&gt;\r\n\t&lt;div class=\&quot;search_result_friend\&quot;&gt;\r\n\t\t\t&lt;\/div&gt;\r\n\t&lt;div class=\&quot;mediumHolder_default\&quot; data-miniprofile=\&quot;13815649\&quot; style=\&quot;float:left;\&quot;&gt;&lt;div class=\&quot;avatarMedium\&quot;&gt;&lt;a href=\&quot;http:\/\/steamcommunity.com\/id\/edgarssults\&quot;&gt;&lt;img s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserSearchResponse {
            get {
                return ResourceManager.GetString("UserSearchResponse", resourceCulture);
            }
        }
    }
}
